time = ("Corinthians", "Palmeiras", "Santos", "Gremio", "Cruzeiro", "Flamengo", "Vasco", "Chapecoense", "Atletico", "Botafogo", "Atletico-pr", "Bahia", "São Paulo", "Fluminence", "Sport Recife", "EC Vitoria", "Coritiba", "Avai", "Ponte preta", "Atletico-GO")
print(f'Lista de Times: {time}')
print("-=-="*7)
print(f"Os 5 primeiros colocados são {time[0:5]}")
print("-=-="*7)
print(f"Os 4 ultimos são {time[-4:]}")
print(f"Times em ordem alfabetica: {sorted(time)}")
print("-=-="*7)
print(f"E a chapecoense esta na {len(time[9])}° posição")